#!/usr/bin/env bash
# scaffold.sh — deterministic offline project scaffolder (cli-app-generator v2, spike F).
# Contract: stdout = data-only (one line per generated file); all logs -> stderr.
# Exit codes: 0 ok | 1 usage | 2 runtime.
set -euo pipefail
export LC_ALL=C

VERSION="0.1.0"
TIER="" AUDIENCE="" NAME="" DEST=""
PROFILES="no" QUIET="no" DRY_RUN="no"
RUN_LINE="" AUDIENCE_NOTE=""

usage() {
  cat <<'EOF'
scaffold.sh — deterministic offline project scaffolder (spike F)

usage: scaffold.sh --tier TIER --audience AUD --name NAME --dest DIR [flags]

params:
  --tier TIER       python-project | go-cli | bash-tool
  --audience AUD    human | agent
  --name NAME       CLI name, single token
  --dest DIR        destination directory (must not exist)
flags:
  --profiles        include agent-profile extras (default: off)
  --no-profiles     explicitly exclude agent-profile extras
  --dry-run         log planned actions to stderr, write nothing
  -q, --quiet       suppress stderr log lines
  -h, --help        show this help
  --version         print version
EOF
}

log()  { [[ $QUIET == yes ]] || printf 'scaffold: %s\n' "$*" >&2; }
data() { printf '%s\n' "$*"; }
die()  { printf 'scaffold: error: %s\n' "$*" >&2; exit 2; }
usage_err() { printf 'scaffold: error: %s\n' "$*" >&2; usage >&2; exit 1; }

[[ $# -gt 0 ]] || usage_err "no arguments; try --help"

while [[ $# -gt 0 ]]; do
  case $1 in
    --tier)       [[ $# -ge 2 ]] || usage_err "--tier needs a value"; TIER=$2; shift 2 ;;
    --audience)   [[ $# -ge 2 ]] || usage_err "--audience needs a value"; AUDIENCE=$2; shift 2 ;;
    --name)       [[ $# -ge 2 ]] || usage_err "--name needs a value"; NAME=$2; shift 2 ;;
    --dest)       [[ $# -ge 2 ]] || usage_err "--dest needs a value"; DEST=$2; shift 2 ;;
    --profiles)   PROFILES=yes; shift ;;
    --no-profiles) PROFILES=no; shift ;;
    --dry-run)    DRY_RUN=yes; shift ;;
    -q|--quiet)   QUIET=yes; shift ;;
    -h|--help)    usage; exit 0 ;;
    --version)    printf 'scaffold.sh %s\n' "$VERSION"; exit 0 ;;
    *)            usage_err "unknown argument: $1" ;;
  esac
done

validate() {
  [[ -n $TIER ]] || usage_err "--tier is required (python-project|go-cli|bash-tool)"
  case $TIER in python-project|go-cli|bash-tool) ;; *) usage_err "unknown tier: $TIER" ;; esac
  [[ -n $AUDIENCE ]] || usage_err "--audience is required (human|agent)"
  case $AUDIENCE in human|agent) ;; *) usage_err "unknown audience: $AUDIENCE" ;; esac
  [[ -n $NAME ]] || usage_err "--name is required"
  [[ $NAME =~ ^[a-z][a-z0-9_-]*$ ]] || usage_err "invalid name '$NAME' (want ^[a-z][a-z0-9_-]*\$)"
  [[ -n $DEST ]] || usage_err "--dest is required"
  if [[ -e $DEST && $DRY_RUN == no ]]; then die "destination exists: $DEST (remove it first)"; fi
}

# Escape sed replacement metachars (| is the substitution delimiter).
esc_sed() { sed -e 's/[|&\\]/\\&/g' <<<"$1"; }

# Apply @@PLACEHOLDER@@ substitution to stdin, emit to stdout.
subst() {
  sed -e "s|@@NAME@@|$(esc_sed "$NAME")|g" \
      -e "s|@@TIER@@|$(esc_sed "$TIER")|g" \
      -e "s|@@AUDIENCE@@|$(esc_sed "$AUDIENCE")|g" \
      -e "s|@@RUN_LINE@@|$(esc_sed "$RUN_LINE")|g" \
      -e "s|@@AUDIENCE_NOTE@@|$(esc_sed "$AUDIENCE_NOTE")|g"
}

# emit REL_PATH [MODE] — render stdin into $DEST/REL_PATH. Per-file line -> stdout.
emit() {
  local rel=$1 mode=${2:-}
  local target="$DEST/$rel"
  if [[ $DRY_RUN == yes ]]; then printf 'scaffold: dry-run: create %s\n' "$rel" >&2; return 0; fi
  mkdir -p "$(dirname "$target")"
  subst > "$target"
  [[ $mode == 755 ]] && chmod 755 "$target"
  data "$rel"
}

resolve_derived() {
  case $TIER in
    python-project) RUN_LINE="python3 src/$NAME.py" ;;
    go-cli)         RUN_LINE="go run ." ;;
    bash-tool)      RUN_LINE="./bin/$NAME" ;;
  esac
  case $AUDIENCE in
    agent) AUDIENCE_NOTE="stdout is data-only; logs and prompts go to stderr." ;;
    human) AUDIENCE_NOTE="Human-friendly output by default; pass --json for agent consumption." ;;
  esac
}

emit_readme() {
  emit README.md <<'EOF'
# @@NAME@@

Generated CLI skeleton — tier: @@TIER@@, audience: @@AUDIENCE@@.

## Run

@@RUN_LINE@@

## Audience notes

- @@AUDIENCE_NOTE@@
- exit codes: 0 ok | 1 usage | 2 runtime | 3 upstream | 4 internal.
EOF
}

emit_main() {
  emit "src/$NAME.py" 755 <<'EOF'
#!/usr/bin/env python3
"""@@NAME@@ — generated by cli-app-generator v2 (tier=@@TIER@@, audience=@@AUDIENCE@@)."""


def main() -> int:
    print("@@NAME@@ ready (tier=@@TIER@@, audience=@@AUDIENCE@@)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
EOF
}

# Per-tier file sets: each branch owns its extra files; README + main are shared.
emit_tier_files() {
  emit_readme
  case $TIER in
    python-project)
      emit_main
      ;;
    go-cli)
      emit_main
      emit go.mod <<'EOF'
module @@NAME@@

go 1.22
EOF
      ;;
    bash-tool)
      emit "bin/$NAME" 755 <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
echo "@@NAME@@ ready (tier=bash-tool, audience=@@AUDIENCE@@)"
EOF
      ;;
  esac
}

# Feature flag via case: agent-profile extras.
emit_extras() {
  case $PROFILES in
    yes) emit AGENT_PROFILE.md <<'EOF'
# Agent profile extras

stdout: data only. stderr: logs and prompts.
exit codes: 0 ok | 1 usage | 2 runtime | 3 upstream | 4 internal.
EOF
    ;;
  esac
}

main() {
  validate
  resolve_derived
  if [[ $DRY_RUN == yes ]]; then
    log "dry-run for $DEST (nothing written)"
  else
    mkdir -p "$DEST"
  fi
  emit_tier_files
  emit_extras
  log "done: $DEST"
}

main
