#!/usr/bin/env python3
"""demo — generated by cli-app-generator v2 (tier=python-project, audience=agent)."""


def main() -> int:
    print("demo ready (tier=python-project, audience=agent)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
