# toytool completion                                       -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_toytool_completions_node_flag_state() {
  case "$1:$2" in
    0:--help|0:-h) return 0 ;;
    0:--version|0:-v) return 0 ;;
    1:--output) return 2 ;;
    1:--help|1:-h) return 0 ;;
    2:--help|2:-h) return 0 ;;
    2:--dry-run) return 0 ;;
    2:--yes|2:-y) return 0 ;;
    3:--help|3:-h) return 0 ;;
  esac

  return 1
}

_toytool_completions_option_seen() {
  local completed_option option_name
  for completed_option in "${completed_options[@]}"; do
    for option_name in "$@"; do
      [[ "$completed_option" == "$option_name" ]] && return 0
    done
  done

  return 1
}

_toytool_completions_resolve_node() {
  node_id=0
  node_word_count=0
  positional_index=0

  local word
  for word in "${non_options[@]}"; do
    case "$node_id:$word" in
      0:show)
        node_id=1
        node_word_count=1
        ;;
      0:delete)
        node_id=2
        node_word_count=1
        ;;
      0:completions)
        node_id=3
        node_word_count=1
        ;;
      *)
        break
        ;;
    esac
  done

  positional_index=$((${#non_options[@]} - node_word_count))
}

_toytool_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=
  if ((COMP_CWORD > 0)); then
    prev=${COMP_WORDS[$((COMP_CWORD - 1))]}
  fi

  local completed=()
  if ((COMP_CWORD > 1)); then
    completed=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  local non_options=()
  local completed_options=()
  local node_id=
  local node_word_count=-1
  local positional_index=0
  local invalid_completion=0
  local flag_state=0
  _toytool_completions_resolve_node

  local skip_next=0
  for word in "${completed[@]}"; do
    if ((skip_next)); then
      skip_next=0
      continue
    fi

    if [[ "${word:0:1}" == "-" ]]; then
      _toytool_completions_node_flag_state "$node_id" "$word"
      flag_state=$?
      if (( flag_state == 1 )); then
        invalid_completion=1
        break
      fi

      completed_options+=("$word")
      if (( flag_state == 2 )); then
        skip_next=1
      fi
      continue
    fi

    non_options+=("$word")
    _toytool_completions_resolve_node
  done

  COMPREPLY=()
  (( invalid_completion )) && return

  case "$node_id:$prev" in
    1:--output)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "table json csv tsv" -- "$cur")
      return
      ;;
  esac

  if [[ "${cur:0:1}" != "-" ]] && (( positional_index == 0 )); then
    case "$node_id" in
      0)
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "show delete completions" -- "$cur")
        return
        ;;
    esac
  fi

  if [[ "${cur:0:1}" == "-" ]]; then
    case "$node_id" in
      0)
        local words=()
        _toytool_completions_option_seen "--help" "-h" || words+=("--help" "-h")
        _toytool_completions_option_seen "--version" "-v" || words+=("--version" "-v")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      1)
        local words=()
        _toytool_completions_option_seen "--help" "-h" || words+=("--help" "-h")
        _toytool_completions_option_seen "--output" || words+=("--output")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      2)
        local words=()
        _toytool_completions_option_seen "--help" "-h" || words+=("--help" "-h")
        _toytool_completions_option_seen "--dry-run" || words+=("--dry-run")
        _toytool_completions_option_seen "--yes" "-y" || words+=("--yes" "-y")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      3)
        local words=()
        _toytool_completions_option_seen "--help" "-h" || words+=("--help" "-h")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
    esac
  fi

  case "$node_id:$positional_index" in
    1:0)
      return
      ;;
    2:0)
      return
      ;;
  esac
} &&
  complete -F _toytool_completions toytool

# ex: filetype=sh
