#!/usr/bin/env python3
"""@@NAME@@ — generated by cli-app-generator v2 (tier=@@TIER@@, audience=@@AUDIENCE@@)."""


def main() -> int:
    print("@@NAME@@ ready (tier=@@TIER@@, audience=@@AUDIENCE@@)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
